unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix
bind-key r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
